# Generated by Django 5.2.1 on 2026-04-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgentSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('groq_api_key', models.CharField(blank=True, max_length=255)),
                ('model_name', models.CharField(default='llama-3.1-8b-instant', max_length=255)),
                ('system_prompt', models.TextField(blank=True)),
                ('training_text', models.TextField(blank=True)),
                ('include_products_context', models.BooleanField(default=True)),
            ],
        ),
    ]
