# Generated by Django 5.2.1 on 2026-04-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='admin_access_pin_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
