# Generated by Django 5.2.1 on 2026-04-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_access_instructions_product_access_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="promotion_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="promotion_end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="promotion_price_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="promotion_start_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
