# Generated by Django 5.2.1 on 2026-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_promotion_enabled_product_promotion_end_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subscription_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="subscription_plans",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
