# Generated by Django 5.2.1 on 2026-04-04 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_purchaseorder_user_last_read_message_id'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseorder',
            name='uniq_order_idempotency_per_user_product_provider',
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('idempotency_key__isnull', True), _negated=True), models.Q(('idempotency_key', ''), _negated=True)), fields=('user', 'product', 'provider', 'idempotency_key'), name='uniq_order_idempotency_per_user_product_provider'),
        ),
    ]
