# Generated by Django 5.2.1 on 2026-04-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_conversationmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='provider_checkout_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
