# Generated by Django 5.2.1 on 2026-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_purchaseorder_provider_checkout_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="purchase_mode",
            field=models.CharField(
                choices=[("one_time", "One Time"), ("subscription", "Subscription")],
                default="one_time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="subscription_billing_period",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="subscription_plan_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="subscription_plan_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
